version: "3.8"
services:
  redis:
    image: redis:8-alpine
    command: ["redis-server","--appendonly","no"]
    ports: ["6379:6379"]
  stunnel:
    image: alpine:3
    depends_on: [redis]
    volumes:
      - ./tls:/etc/stunnel/tls:ro
      - ./stunnel/redis.conf:/etc/stunnel/redis.conf:ro
    command: ["sh","-c","apk add --no-cache stunnel && stunnel /etc/stunnel/redis.conf"]
    ports: ["6380:6380"]
